'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace NinjaManager.Domain

    Partial Public Class Equipment
        Public Property Id As Integer
        Public Property Name As String
        Public Property Price As Integer
        Public Property Category As String
        Public Property Strength As Integer
        Public Property Intel As Integer
        Public Property Agility As Integer
    
        Public Overridable Property Ninjas As ICollection(Of Ninja) = New HashSet(Of Ninja)
    
    End Class

End Namespace
