'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace NinjaManager.Domain

    Partial Public Class MyEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=MyEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property Equipments() As DbSet(Of Equipment)
        Public Overridable Property Ninjas() As DbSet(Of Ninja)
    
    End Class

End Namespace
