'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace NinjaManager.Domain

    Partial Public Class Ninja
        Public Property Id As Integer
        Public Property Name As String
        Public Property Gold_amount As Integer
    
        Public Overridable Property Equipments As ICollection(Of Equipment) = New HashSet(Of Equipment)
    
    End Class

End Namespace
